### PR TITLE
Do not fail test when additional data in the tree

### LINKED ISSUE #131: TCK does not allow additional data in returnedTree
In version 1.1 of TCK, it allows additional fields in the returnedTree which are not checked by the test.   It allows JAX-RS failed method (not annotated with `@Traced`) to have `error=true` and exception logged. In version 1.2, #94 changed this behavior and some tests failed when returnedTree contains `error=true`.

### PR DESCRIPTION
**Pull request by fmhwong**
Fixes #131 

1. Create a new assertEqualErrorTrees() to check for returnedTree which expects an error.
1. Switch testAnnotationException() to call assertEqualErrorTrees()
1. Fix the url for `/metrics/base`

Signed-off-by: Felix Wong <fmhwong@ca.ibm.com>

### CODE REVIEW

**Comment by fmhwong** [comment]
@pavolloffay please review

File: tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java [hunk 1]
```diff
@@ -227,25 +228,46 @@ protected void assertEqualTrees(ConsumableTree<TestSpan> returnedTree,
...
+                    && !key.equals(Tags.HTTP_METHOD.getKey())
+                    && !key.equals(Tags.HTTP_URL.getKey())
+                    && !key.equals(Tags.HTTP_STATUS.getKey())
+                    && !key.equals(Tags.COMPONENT.getKey())
+                    && !key.equals(TestServerWebServices.LOCAL_SPAN_TAG_KEY));
+        });
+
+        // It's okay if the returnedTree has log entries other than the ones we
+        // want to compare, so just remove those
+        returnedTree.visitTree(span -> span.getLogEntries()
```
Comment (pavolloffay) [inline tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java]: If I understand it correctly the only significant change in this PR is this addition. 

You split the method but also changed client tests to call new method `assertEqualErrorTrees`. If the split is not needed I would prefer to keep it in one method.

Comment (fmhwong) [reply tck/src/main/java/org/eclipse/microprofile/opentracing/tck/OpenTracingBaseTests.java]: The current way is to use to `Tags.SPAN_KIND` to determine to remove the `error`, `event` and `error.obejct` from `logEntries does not work for all cases.  It is more flexible to split them or we need to find another condition to choose which section to run in a combined method.

**Comment by pavolloffay** [comment]
thanks @fmhwong
